module.exports = {
  HOSTNAME: process.env.HOSTNAME,
  PORT: parseInt(process.env.PORT),
  REDIS_URI: process.env.REDIS_URI,
  SERVER_URL: process.env.SERVER_URL,
  AUTH_REDIRECT_URL: process.env.AUTH_REDIRECT_URL,
  ONEDRIVE_UPLOAD_URL: process.env.ONEDRIVE_UPLOAD_URL,
  ONEDRIVE_ITEM_URL: process.env.ONEDRIVE_ITEM_URL,
  DROPBOX_UPLOAD_URL: process.env.DROPBOX_UPLOAD_URL,
  DROPBOX_UPLOAD_STATUS_URL: process.env.DROPBOX_UPLOAD_STATUS_URL,
  GOOGLE_DRIVE_APP_ID: process.env.GOOGLE_DRIVE_APP_ID,
  GOOGLE_DRIVE_APP_PASSWD: process.env.GOOGLE_DRIVE_APP_PASSWD,
  TEMP_DIR: process.env.TEMP_DIR,
  TOKEN_EXP_TIME: parseInt(process.env.TOKEN_EXP_TIME)
};
