export default {
  PUBLIC_URL: process.env.PUBLIC_URL,
  SERVER_URL: process.env.REACT_APP_SERVER_URL,
  AUTH_REDIRECT_URI: process.env.REACT_APP_AUTH_REDIRECT_URI,
  ONEDRIVE_APP_ID: process.env.REACT_APP_ONEDRIVE_APP_ID,
  ONEDRIVE_APP_PASSWD: process.env.REACT_APP_ONEDRIVE_APP_PASSWD,
  DROPBOX_APP_ID: process.env.REACT_APP_DROPBOX_APP_ID,
  DROPBOX_APP_PASSWD: process.env.REACT_APP_DROPBOX_APP_PASSWD,
  GOOGLE_DRIVE_APP_ID: process.env.REACT_APP_GOOGLE_DRIVE_APP_ID,
  GOOGLE_DRIVE_APP_PASSWD: process.env.REACT_APP_GOOGLE_DRIVE_APP_PASSWD
};
